### PR TITLE
Revert "Uses `install_requires` in setup.py, fixes #27"

### LINKED ISSUE #27: ValueError: expected parenthesized list: '==2.18.4'
```
$ pip install https://github.com/corpetty/py-etherscan-api/archive/f45a313.zip#egg=py-etherscan-api
Collecting py-etherscan-api from https://github.com/corpetty/py-etherscan-api/archive/f45a313.zip#egg=py-etherscan-api
  Downloading https://github.com/corpetty/py-etherscan-api/archive/f45a313.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jilk_tj9/py-etherscan-api/setup.py", line 13, in <module>
        'requests==2.18.4',
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/andre/workspace/py-etherscan-api/venv/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 253, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/lib/python3.6/distutils/dist.py", line 1207, in set_requires
        distutils.versionpredicate.VersionPredicate(v)
      File "/usr/lib/python3.6/distutils/versionpredicate.py", line 114, in __init__
        raise ValueError("expected parenthesized list: %r" % paren)
    ValueError: expected parenthesized list: '==2.18.4'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jilk_tj9/py-etherscan-api/
```

This is because we should use `install_requires` rather than `requires` in `setup.py`, I'll provide a pull request.

### PR DESCRIPTION
**Pull request by PEPEInvest**

### CODE REVIEW

**Comment by AndreMiras** [comment]
Hi @PEPEInvest could you explain why this change is required?
I actually added this `install_requires` because we couldn't install the package otherwise, see https://github.com/corpetty/py-etherscan-api/issues/27

**Comment by corpetty** [comment]
I haven't testing this myself, so I can't merge. I won't have time to test until next week either.  Anyone have any input on this?

**Comment by AndreMiras** [comment]
Well it's quite easy to test, but it doesn't work, that's why I asked, why he proposed that revert (from one of my previous PR).
See:
```
$ pip install https://github.com/PEPEcoin/py-etherscan-api/archive/revert-28-feature/setup_install_requires.zip
Collecting https://github.com/PEPEcoin/py-etherscan-api/archive/revert-28-feature/setup_install_requires.zip
  Downloading https://github.com/PEPEcoin/py-etherscan-api/archive/revert-28-feature/setup_install_requires.zip
     | 30kB 325kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-yvjo8lwu/setup.py", line 13, in <module>
        'requests==2.18.4',
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/trash/venv/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 253, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/lib/python3.6/distutils/dist.py", line 1207, in set_requires
        distutils.versionpredicate.VersionPredicate(v)
      File "/usr/lib/python3.6/distutils/versionpredicate.py", line 114, in __init__
        raise ValueError("expected parenthesized list: %r" % paren)
    ValueError: expected parenthesized list: '==2.18.4'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-yvjo8lwu/
```
So yes I don't really understand that pull request, I'd like to know more.

**Comment by PEPEInvest** [comment]
Let´s  Go

**Comment by corpetty** [comment]
once again, please provide explanation and reasoning.

**Pull request closed without merging**
