### PR TITLE
Added client errors to indicate the problems

### PR DESCRIPTION
**Pull request by d3QUone**
* Removed silent `exit` and `quit`
* Added classic exceptions
* Added python dependencies

### CODE REVIEW

**Comment by AndreMiras** [comment]
Nice pull request, I came here to write that pull request, it's a shame it's still not integrated.
This is also related to https://github.com/corpetty/py-etherscan-api/issues/19

**Comment by airboat** [comment]
thanks

**Comment by corpetty** [comment]
Been away from this lately... I will review and incorporate today hopefully

**Comment by d3QUone** [comment]
👍

**Comment by taylorjdawson** [comment]
Nice work guys!

**Pull request merged**
